### ISSUE TITLE
Any chance there is a version of this with Portugal and Andorra added for a Peninsula map?

### ISSUE THREAD

**Issue by ghost** [javiertoledo/spain-map#1]
I'd love to have this with Portugal and Andorra also in the map. Do you know if there's any fork of this map that has them or did you think about it?

Thanks!

**Comment by javiertoledo** [comment]
I have no plans about doing this, but you can build a new map with a different set of territories if you change the data in the `spainMap` array https://github.com/javiertoledo/spain-map/blob/master/lib/spain-map.js#L5

You can use the `jsonize.rb` script in the utils directory (https://github.com/javiertoledo/spain-map/tree/master/utils) to build a new map from a different SVG image.
